-- MySQL Script generated by MySQL Workbench
-- dc 22 ago 2018 11:42:56 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdllibres
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdllibres` ;

-- -----------------------------------------------------
-- Schema bdllibres
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdllibres` DEFAULT CHARACTER SET utf8mb4 ;
USE `bdllibres` ;

-- -----------------------------------------------------
-- Table `bdllibres`.`Classificacio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Classificacio` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Classificacio` (
  `idcla` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `codi` INT NOT NULL,
  PRIMARY KEY (`idcla`),
  UNIQUE INDEX `codi_UNIQUE` (`codi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Subclassificacio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Subclassificacio` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Subclassificacio` (
  `idsub` INT NOT NULL AUTO_INCREMENT,
  `classi` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `codi` INT NOT NULL,
  PRIMARY KEY (`idsub`),
  INDEX `fk_subclassificacio_classificacio_idx` (`classi` ASC),
  CONSTRAINT `fk_subclassificacio_classificacio`
    FOREIGN KEY (`classi`)
    REFERENCES `bdllibres`.`Classificacio` (`idcla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Subsubclassificacio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Subsubclassificacio` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Subsubclassificacio` (
  `idsubsub` INT NOT NULL AUTO_INCREMENT,
  `subclassi` INT NOT NULL,
  `nom` VARCHAR(100) NOT NULL,
  `codi` INT NOT NULL,
  PRIMARY KEY (`idsubsub`),
  INDEX `fk_subclassificacio_subclassificacio1_idx` (`subclassi` ASC),
  CONSTRAINT `fk_subclassificacio_subclassificacio1`
    FOREIGN KEY (`subclassi`)
    REFERENCES `bdllibres`.`Subclassificacio` (`idsub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Escriptor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Escriptor` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Escriptor` (
  `idescriptor` INT NOT NULL AUTO_INCREMENT,
  `autor` VARCHAR(100) NOT NULL,
  `codi` VARCHAR(5) NOT NULL,
  `es_colleccio` TINYINT(1) NOT NULL DEFAULT 0,
  `img_dir` VARCHAR(10) NULL,
  `biografia` LONGTEXT NULL,
  PRIMARY KEY (`idescriptor`),
  UNIQUE INDEX `codi_UNIQUE` (`codi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Idiomes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Idiomes` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Idiomes` (
  `ididiomes` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ididiomes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Usuaris`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Usuaris` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Usuaris` (
  `idusuari` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(32) NOT NULL,
  `codi` VARCHAR(2) NOT NULL,
  `contrassenya` VARCHAR(40) NOT NULL,
  `permisos` INT NOT NULL,
  PRIMARY KEY (`idusuari`),
  UNIQUE INDEX `codi_UNIQUE` (`codi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Llibre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Llibre` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Llibre` (
  `idllibre` INT NOT NULL AUTO_INCREMENT,
  `classi` INT NOT NULL,
  `autor_principal` INT NOT NULL,
  `propietari` INT NOT NULL,
  `num_llibre` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `data_modificacio` DATETIME NOT NULL,
  `idioma` INT NOT NULL,
  `img_dir` VARCHAR(10) NULL,
  `editorial` VARCHAR(45) NULL,
  `ISBN` VARCHAR(15) NULL,
  `any_edicio` YEAR NULL,
  `any` YEAR NULL,
  `data_compra` DATE NULL,
  `lloc_compra` VARCHAR(45) NULL,
  `descripcio` LONGTEXT NULL,
  `pagines` INT NULL,
  PRIMARY KEY (`idllibre`),
  INDEX `fk_llibre_subsubclassificacio1_idx` (`classi` ASC),
  INDEX `fk_llibre_escriptor1_idx` (`autor_principal` ASC),
  INDEX `fk_Llibre_Idiomes1_idx` (`idioma` ASC),
  INDEX `fk_Llibre_Usuaris1_idx` (`propietari` ASC),
  CONSTRAINT `fk_llibre_subsubclassificacio1`
    FOREIGN KEY (`classi`)
    REFERENCES `bdllibres`.`Subsubclassificacio` (`idsubsub`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_llibre_escriptor1`
    FOREIGN KEY (`autor_principal`)
    REFERENCES `bdllibres`.`Escriptor` (`idescriptor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Llibre_Idiomes1`
    FOREIGN KEY (`idioma`)
    REFERENCES `bdllibres`.`Idiomes` (`ididiomes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Llibre_Usuaris1`
    FOREIGN KEY (`propietari`)
    REFERENCES `bdllibres`.`Usuaris` (`idusuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Critiques`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Critiques` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Critiques` (
  `idcritiques` INT NOT NULL AUTO_INCREMENT,
  `usuari` INT NOT NULL,
  `llibre` INT NOT NULL,
  `llegit` INT NOT NULL DEFAULT 0,
  `critica` LONGTEXT NULL,
  `data_critica` DATETIME NULL,
  PRIMARY KEY (`idcritiques`, `usuari`, `llibre`),
  INDEX `fk_Critiques_Usuari1_idx` (`usuari` ASC),
  INDEX `fk_Critiques_Llibre1_idx` (`llibre` ASC),
  CONSTRAINT `fk_Critiques_Usuari1`
    FOREIGN KEY (`usuari`)
    REFERENCES `bdllibres`.`Usuaris` (`idusuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Critiques_Llibre1`
    FOREIGN KEY (`llibre`)
    REFERENCES `bdllibres`.`Llibre` (`idllibre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Prestec`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Prestec` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Prestec` (
  `idprestec` INT NOT NULL AUTO_INCREMENT,
  `llibre` INT NOT NULL,
  `usuari` INT NOT NULL,
  `data_prestec` DATETIME NOT NULL,
  `informacio` VARCHAR(45) NOT NULL,
  `tornat` TINYINT(1) NOT NULL DEFAULT 0,
  `data_tornat` DATETIME NULL,
  PRIMARY KEY (`idprestec`),
  INDEX `fk_Prestec_Llibre1_idx` (`llibre` ASC),
  INDEX `fk_Prestec_Usuari1_idx` (`usuari` ASC),
  CONSTRAINT `fk_Prestec_Llibre1`
    FOREIGN KEY (`llibre`)
    REFERENCES `bdllibres`.`Llibre` (`idllibre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Prestec_Usuari1`
    FOREIGN KEY (`usuari`)
    REFERENCES `bdllibres`.`Usuaris` (`idusuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdllibres`.`Autorssecundaris`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdllibres`.`Autorssecundaris` ;

CREATE TABLE IF NOT EXISTS `bdllibres`.`Autorssecundaris` (
  `Llibre_idllibre` INT NOT NULL,
  `Escriptor_idescriptor` INT NOT NULL,
  PRIMARY KEY (`Llibre_idllibre`, `Escriptor_idescriptor`),
  INDEX `fk_Llibre_has_Escriptor_Escriptor1_idx` (`Escriptor_idescriptor` ASC),
  INDEX `fk_Llibre_has_Escriptor_Llibre1_idx` (`Llibre_idllibre` ASC),
  CONSTRAINT `fk_Llibre_has_Escriptor_Llibre1`
    FOREIGN KEY (`Llibre_idllibre`)
    REFERENCES `bdllibres`.`Llibre` (`idllibre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Llibre_has_Escriptor_Escriptor1`
    FOREIGN KEY (`Escriptor_idescriptor`)
    REFERENCES `bdllibres`.`Escriptor` (`idescriptor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
